included:
  - Source
  - Example/SplashAd.Swift
  - Example/Tests
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
disabled_rules:
  - identifier_name
  - type_name
  - force_cast
  - function_body_length
  - type_body_length
  - file_length
  - line_length
  - for_where
  - function_parameter_count
  - large_tuple
  - nesting
  - trailing_whitespace
  - notification_center_detachment
  - multiple_closures_with_trailing_closure
  - todo
  - cyclomatic_complexity
  - block_based_kvo
  - fallthrough  
  - weak_delegate
  - vertical_parameter_alignment
  - switch_case_alignment
number_separator:
  minimum_length: 5