# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Demo' do
  use_frameworks!
  pod 'SplashAd.Swift', :path => '../'

  target 'DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoUITests' do
    # Pods for testing
  end

end
